name: 'build frontend'
on:
  workflow_call:

jobs:
  build: 
    runs-on: [ ubuntu-latest ]
    steps:
      - name: 'â¬‡ï¸ Checkout code'
        uses: actions/checkout@v3
      - name: 'ğŸ—ï¸ Setup dotnet'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: 'ğŸ—ï¸ dotnet restore'
        run: dotnet restore
      - name: 'ğŸ—ï¸ dotnet build'
        run: dotnet build
      - name: 'ğŸ—ï¸ dotnet publish'
        run: dotnet publish
      - name: 'ğŸ§ª Test with dotnet'
        run: dotnet test --logger trx --results-directory "TestResults"
      - name: 'â¬†ï¸ Upload build artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            Frontend/bin/Release/*